name: Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Send Question
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
          -d "chat_id=$CHAT_ID" \
          -d "text=ğŸ“š *Daily Exam Dose*

âœ… Question 1
ğŸ“– Subject: Physics
ğŸ« Class: 11

â“ What is force?

A. Mass Ã— Acceleration
B. Mass Ã· Acceleration
C. Mass + Acceleration
D. Mass - Acceleration

âœ… Answer: A" \
          -d "parse_mode=Markdown"
